# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: global_api.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'global_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import morphling_pb2 as morphling__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10global_api.proto\x12\x14morphling.global_api\x1a\x0fmorphling.proto\"\x93\x01\n\x15\x44\x65viceRegisterRequest\x12\x0c\n\x04uuid\x18\x01 \x02(\x04\x12\r\n\x05\x66lops\x18\x02 \x02(\x04\x12\x0e\n\x06memory\x18\x03 \x02(\x04\x12\r\n\x05ul_bw\x18\x04 \x02(\x04\x12\r\n\x05\x64l_bw\x18\x05 \x02(\x04\x12\x0e\n\x06ul_lat\x18\x06 \x02(\x04\x12\x0e\n\x06\x64l_lat\x18\x07 \x02(\x04\x12\x0f\n\x07\x62\x61\x63kend\x18\x08 \x02(\x04\"\xd9\x01\n\x12\x43omputeGemmRequest\x12\x0f\n\x07version\x18\x01 \x02(\x04\x12\x0b\n\x03row\x18\x02 \x02(\x03\x12\x0b\n\x03\x63ol\x18\x03 \x02(\x03\x12\r\n\x05pivot\x18\x04 \x02(\x03\x12\r\n\x05h_dim\x18\x05 \x02(\x03\x12\x0e\n\x06\x64\x65v_id\x18\x06 \x02(\x03\x12\x0b\n\x03oid\x18\x07 \x02(\x03\x12\x11\n\ttimestamp\x18\x08 \x02(\x04\x12$\n\x08matrix_a\x18\n \x01(\x0b\x32\x12.morphling.Payload\x12$\n\x08matrix_b\x18\x14 \x01(\x0b\x32\x12.morphling.Payload\"\xb4\x01\n\x13\x43omputeGemmResponse\x12\x0f\n\x07version\x18\x01 \x02(\x04\x12\x0b\n\x03row\x18\x02 \x02(\x03\x12\x0b\n\x03\x63ol\x18\x03 \x02(\x03\x12\r\n\x05pivot\x18\x04 \x02(\x03\x12\r\n\x05h_dim\x18\x05 \x02(\x03\x12\x0e\n\x06\x64\x65v_id\x18\x06 \x02(\x03\x12\x0b\n\x03oid\x18\x07 \x02(\x03\x12\x11\n\ttimestamp\x18\x08 \x02(\x04\x12$\n\x08matrix_c\x18\n \x02(\x0b\x32\x12.morphling.Payload*\x86\x01\n\x0bMessageType\x12\x10\n\x0c\x42\x45GINNING_ID\x10\x64\x12\x0b\n\x07UNKNOWN\x10\x65\x12\x18\n\x14\x43OMPUTE_GEMM_REQUEST\x10\x66\x12\x19\n\x15\x43OMPUTE_GEMM_RESPONSE\x10g\x12\x13\n\x0f\x44\x45VICE_REGISTER\x10h\x12\x0e\n\tENDING_ID\x10\xc8\x01:W\n\x14\x63ompute_gemm_request\x12\x0f.morphling.Body\x18\x65 \x01(\x0b\x32(.morphling.global_api.ComputeGemmRequest:Y\n\x15\x63ompute_gemm_response\x12\x0f.morphling.Body\x18\x66 \x01(\x0b\x32).morphling.global_api.ComputeGemmResponse:U\n\x0fregister_device\x12\x0f.morphling.Body\x18g \x01(\x0b\x32+.morphling.global_api.DeviceRegisterRequest')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'global_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPE']._serialized_start=613
  _globals['_MESSAGETYPE']._serialized_end=747
  _globals['_DEVICEREGISTERREQUEST']._serialized_start=60
  _globals['_DEVICEREGISTERREQUEST']._serialized_end=207
  _globals['_COMPUTEGEMMREQUEST']._serialized_start=210
  _globals['_COMPUTEGEMMREQUEST']._serialized_end=427
  _globals['_COMPUTEGEMMRESPONSE']._serialized_start=430
  _globals['_COMPUTEGEMMRESPONSE']._serialized_end=610
# @@protoc_insertion_point(module_scope)
